<a href="https://colab.research.google.com/github/donguyenquynhnhu/Public/blob/main/Lab6_sohoa.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import torch

torch.cuda.is_available()


True

In [16]:
import torch
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt


df = pd.read_csv("/content/Iris.csv")
df.head()

Id  SepalLengthCm  SepalWidthCm  PetalLengthCm  PetalWidthCm      Species
0   1            5.1           3.5            1.4           0.2  Iris-setosa
1   2            4.9           3.0            1.4           0.2  Iris-setosa
2   3            4.7           3.2            1.3           0.2  Iris-setosa
3   4            4.6           3.1            1.5           0.2  Iris-setosa
4   5            5.0           3.6            1.4           0.2  Iris-setosa

In [15]:
from sklearn.preprocessing import LabelEncoder
from sklearn.model_selection import train_test_split

le = LabelEncoder()
x = df.drop(["Species"], axis=1).values
y = le.fit_transform(df["Species"].values)

x_train, x_test, y_train, y_test = train_test_split(x, y, test_size = 0.2,random_state = 42)

x_train = torch.FloatTensor(x_train)
x_test = torch.FloatTensor(x_test)
y_train = torch.LongTensor(y_train).reshape(-1,1)
y_test = torch.LongTensor(y_test).reshape(-1,1)
print(f"train size : {len(y_train)}")


train size : 120


In [14]:
labels, counts = y_train.unique(return_counts=True)
print(labels, counts)

tensor([0, 1, 2]) tensor([40, 41, 39])


In [19]:
import torch

# Tạo tensor x với requires_grad=True để tính đạo hàm
x = torch.tensor(2.0, requires_grad=True)

# Định nghĩa hàm số y
y = 2*x**4 + x**3 + 3*x**2 + 5*x + 1

# Tính đạo hàm của y theo x
y.backward()

# In ra đạo hàm y'
print("Đạo hàm y':", x.grad)

Đạo hàm y': tensor(93.)


In [26]:
import torch

# Tạo một tensor với requires_grad được đặt thành True
x = torch.tensor(2.0, requires_grad=True)

# Định nghĩa một hàm số sử dụng x
y = x**2 + 3*x + 1

# Tính gradient của y theo x
y.backward()

#  giá trị của x và gradient của x
print("Giá trị của x:", x)
print("Gradient của x (x.grad):", x.grad)

Giá trị của x: tensor(2., requires_grad=True)
Gradient của x (x.grad): tensor(7.)


In [25]:
import torch

# Tạo một tensor x với requires_grad=True
x = torch.tensor(2.0, requires_grad=True)

# Định nghĩa hàm số y
y = 2*x**4 + x**3 + 3*x**2 + 5*x + 1

#  giá trị của y
print("Giá trị của y:", y)

# Thực hiện truyền ngược và tính toán các gradient
y.backward()

#  kết quả đạo hàm
print("Đạo hàm y' (x.grad):", x.grad)

Giá trị của y: tensor(63., grad_fn=<AddBackward0>)
Đạo hàm y' (x.grad): tensor(93.)


In [28]:
import torch

# Tạo một tensor x với requires_grad=True
x = torch.tensor(1.0, requires_grad=True)  # Thay đổi giá trị của x tại đây

# Định nghĩa hàm số y
y = 5*x**6 + 3*x**3 + 2*x + x + 2*x + 5*x**4 + 1

# Giá trị của y
print("Giá trị của y:", y)

# Thực hiện truyền ngược và tính toán các gradient
y.backward()

# Kết quả đạo hàm (gradient của x)
print("Độ dốc (gradient) của y tại x =", x.item(), "là:", x.grad.item())

Giá trị của y: tensor(19., grad_fn=<AddBackward0>)
Độ dốc (gradient) của y tại x = 1.0 là: 64.0


In [29]:
#BTVN1
import torch

# Tạo tensor x với giá trị ban đầu là 2.0 và yêu cầu tính gradient
x = torch.tensor(2.0, requires_grad=True)

# Định nghĩa learning rate
alpha = 0.1

# Số vòng lặp
num_iterations = 10

# Gradient Descent
for i in range(num_iterations):
    # Định nghĩa hàm số y
    y = x**3 + 2*x**2 + 5*x + 1

    # Tính gradient của y theo x
    y.backward()

    # Giá trị của x và gradient tại mỗi vòng lặp
    print(f"Iteration {i+1}: x = {x.item()}, dy/dx = {x.grad.item()}")

    # Cập nhật giá trị của x bằng Gradient Descent
    with torch.no_grad():
        x -= alpha * x.grad

    # Đặt lại gradient về 0 để chuẩn bị cho vòng lặp tiếp theo
    x.grad.zero_()

Iteration 1: x = 2.0, dy/dx = 25.0
Iteration 2: x = -0.5, dy/dx = 3.75
Iteration 3: x = -0.875, dy/dx = 3.796875
Iteration 4: x = -1.2546875476837158, dy/dx = 4.703972339630127
Iteration 5: x = -1.7250847816467285, dy/dx = 7.027413368225098
Iteration 6: x = -2.427826166152954, dy/dx = 12.971714973449707
Iteration 7: x = -3.7249975204467773, dy/dx = 31.726829528808594
Iteration 8: x = -6.897680282592773, dy/dx = 120.14325714111328
Iteration 9: x = -18.912006378173828, dy/dx = 1002.3439331054688
Iteration 10: x = -119.14640808105469, dy/dx = 42116.01171875


In [30]:
import torch
import numpy as np

# 1. Tạo tập dữ liệu giả lập
np.random.seed(42)
x = np.random.randint(1, 11, size=20)  # Số giờ học từ 1 đến 10
noise = np.random.normal(0, 1, size=20)  # Noise nhỏ
y = 3 * x + 5 + noise  # Công thức tính y

# Chuyển đổi sang tensor
x = torch.tensor(x, dtype=torch.float32)
y = torch.tensor(y, dtype=torch.float32)

# 2. Khởi tạo tham số w và b ngẫu nhiên
w = torch.randn(1, requires_grad=True)
b = torch.randn(1, requires_grad=True)

# Định nghĩa learning rate
alpha = 0.01

# Số vòng lặp
num_iterations = 100

# Gradient Descent
for i in range(num_iterations):
    # 3. Tính MSE
    y_pred = w * x + b
    mse = torch.mean((y_pred - y) ** 2)

    # 4. Tính gradient
    mse.backward()

    # 5. Cập nhật tham số w và b
    with torch.no_grad():
        w -= alpha * w.grad
        b -= alpha * b.grad

    # Đặt lại gradient về 0 để chuẩn bị cho vòng lặp tiếp theo
    w.grad.zero_()
    b.grad.zero_()

    # Giá trị của MSE và tham số sau mỗi vòng lặp
    if (i+1) % 10 == 0:
        print(f"Iteration {i+1}: MSE = {mse.item()}, w = {w.item()}, b = {b.item()}")

# Kết quả cuối cùng
print(f"Final parameters: w = {w.item()}, b = {b.item()}")

Iteration 10: MSE = 3.324047565460205, w = 3.764265298843384, b = -0.5150746703147888
Iteration 20: MSE = 3.1908068656921387, w = 3.7470922470092773, b = -0.40115249156951904
Iteration 30: MSE = 3.0641045570373535, w = 3.7303450107574463, b = -0.29006117582321167
Iteration 40: MSE = 2.94362211227417, w = 3.7140142917633057, b = -0.18173019587993622
Iteration 50: MSE = 2.8290514945983887, w = 3.698089361190796, b = -0.07609102129936218
Iteration 60: MSE = 2.7201056480407715, w = 3.6825597286224365, b = 0.026923127472400665
Iteration 70: MSE = 2.6165051460266113, w = 3.6674163341522217, b = 0.12737764418125153
Iteration 80: MSE = 2.5179901123046875, w = 3.652649164199829, b = 0.22533603012561798
Iteration 90: MSE = 2.424309730529785, w = 3.638248920440674, b = 0.3208604156970978
Iteration 100: MSE = 2.3352255821228027, w = 3.62420654296875, b = 0.414011150598526
Final parameters: w = 3.62420654296875, b = 0.414011150598526


In [32]:
arr = np.arange(0,5)
x = torch.from_numpy(arr)
print(x)


tensor([0, 1, 2, 3, 4])


In [33]:
arr[0] = 99
print(x)

tensor([99,  1,  2,  3,  4])


In [34]:
#BTVN 3,4

import torch
arr = np.arange(0,5)
x = torch.tensor(arr)
print(x)  # tensor([0, 1, 2, 3, 4])

arr[0] = 99
print(x)  # tensor([0, 1, 2, 3, 4])


# Tạo tensor rỗng với kích thước (2, 3)
x = torch.empty(2, 3)
print(x)
print("               ")
# Tạo tensor chứa toàn số 0 với kích thước (2, 3)
x = torch.zeros(2, 3)
print(x)
print("               ")
# Tạo tensor chứa toàn số 1 với kích thước (2, 3)
x = torch.ones(2, 3)
print(x)
print("               ")
# Tạo tensor với giá trị ngẫu nhiên từ phân phối đều trong khoảng [0, 1) với kích thước (2, 3)
x = torch.rand(2, 3)
print(x)
print("               ")
# Tạo tensor với kích thước (2, 3)
x = torch.tensor([[1, 2, 3], [4, 5, 6]])
print("               ")
# Reshape tensor thành kích thước (3, 2) sử dụng view
y = x.view(3, 2)
print(y)
print("               ")
# Reshape tensor thành kích thước của tensor khác sử dụng view_as
z = torch.tensor([[1, 2], [3, 4], [5, 6]])
y = x.view_as(z)
print(y)

tensor([0, 1, 2, 3, 4])
tensor([0, 1, 2, 3, 4])
tensor([[-4.2201e+01,  4.3107e-41,  9.0593e-32],
        [ 0.0000e+00,  4.4842e-44,  0.0000e+00]])
               
tensor([[0., 0., 0.],
        [0., 0., 0.]])
               
tensor([[1., 1., 1.],
        [1., 1., 1.]])
               
tensor([[0.5024, 0.4913, 0.7162],
        [0.3425, 0.0592, 0.4588]])
               
               
tensor([[1, 2],
        [3, 4],
        [5, 6]])
               
tensor([[1, 2],
        [3, 4],
        [5, 6]])
