In [26]:
import numpy as np
data = [[1,2],[3,4],[5,6]]
mang = np.array(data)
print(mang)

print(mang[0,1])
print(mang[1,0])
print("---")
print(mang[1:,:])
print("---")
print(mang[1:2])
print("---")
print(mang[1:3])
print("---")
print(mang[0:1])
print("---")
print(mang[:,0])
print("---")
print(mang[0:2,0])
print("---")
print(mang[[0,2],0])
print("+++")
print(mang[::2,0])


[[1 2]
 [3 4]
 [5 6]]
2
3
---
[[3 4]
 [5 6]]
---
[[3 4]]
---
[[3 4]
 [5 6]]
---
[[1 2]]
---
[1 3 5]
---
[1 3]
---
[1 5]
+++
[1 5]


In [62]:
x = [
    [1,2,3,4],
    [5,6,7,8],
    [9,10,11,12],
    [13,14,15,16]
]
mang = np.array(x)
print(mang)

#lay 2,6,10,14 -- 7,11 -- 4,7,10 -- 16,15,14,13
print("+++")
print(mang[::1,1])
print("+++")
print(mang[1:3,2])
print("+++")
print(mang[[0,1,2],[3,2,1]])
print("+++")
print(mang[3,::-1])
print("+++")






[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]
 [13 14 15 16]]
+++
[ 2  6 10 14]
+++
[ 7 11]
+++
[ 4  7 10]
+++
[16 15 14 13]
+++


In [14]:
import numpy as np
x = [
    [1,2,3],
    [4,5,6],
    [7,8,9]
]
mang = np.array(x)
print(mang)

#lay 4,5,6 -- 2,5 -- 3,4 -- 9,6,3
print("***")
print(mang[1])
print("***")
print(mang[[0,1],[1,1]])
print("***")
print(mang[[0,1],[2,0]])
print("***")
print(mang[::-1,2])

print("***")
y = [1,2,3,4,5,6,7,8,9,10]
mang_chan = [num for num in y if num % 2 == 0]
print(mang_chan)





[[1 2 3]
 [4 5 6]
 [7 8 9]]
***
[4 5 6]
***
[2 5]
***
[3 4]
***
[9 6 3]
[2, 4, 6, 8, 10]


[2, 4, 6, 8, 10]
